### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by mcanelson** [Alex25820/Universal-Timer#1]
Is there any chance you can make an option to make it work as a number counter? (With the option for the editor to set up the starting number and let it run as needed?) Thanks!

**Comment by Alex25820** [comment]
Hi, sorry for the late response. I added a new counter mode to the timer. When the Counter Mode checkbox is checked the timer will count up (or down) depending on the set Timer Speed. I have attached a quick video as demonstration. Hope this helps.

https://user-images.githubusercontent.com/50142558/188683893-0eef3091-6789-421a-b198-a1b278723760.mp4
