### ISSUE TITLE
v2 not support premiere cc 2020

### ISSUE THREAD

**Issue by kuronekony4n** [Alex25820/Universal-Timer#2]
it's not supported in 2020 and says I need to update premiere, my pc is potato so it can even barely handle cc 2020 so can you make a support for that?

**Comment by Alex25820** [comment]
Hi, thanks for reporting this.

I have looked in to the issue and there doesn't seem to be anything I can do to solve your problem. Adobe no longer provides downloads for Premiere Pro 2020 and I can therefore not recreate the issue myself. Mogrt files created in a later version of After Effects may not always be compatible with old versions of Premiere Pro and from my understanding there is no easy fix for this problem.

My only advice for you would be to try V1 of this tool to see if it is compatible. If not you will have to find another tool or update to a later version of Premiere Pro. Sorry I couldn't help further.
